name: Staging

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta'

env:
  SSH_KEY_FILE_NAME: kelarin.pem
  APP_DIR: kelarin/app/staging/consumer
  COMPRESSED_ARTIFACT_FILE_NAME: build.zip
  ARTIFACT_NAME: build-artifact
  ECOSYSTEM_CONFIG_FILE: ecosystem.staging.config.js

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: STAGING
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Extract environment variables
        run: echo "${{ secrets.ENV_VARS }}" > .env
      - name: Install dependencies
        run: npm install
      - name: Build App
        run: npm run build
      - name: Zip artifact directory
        run: zip -r ${{ env.COMPRESSED_ARTIFACT_FILE_NAME }} build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.COMPRESSED_ARTIFACT_FILE_NAME }}
          retention-days: 7

  deploy:
    runs-on: ubuntu-24.04
    environment: STAGING
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Extract environment variables
        run: echo "${{ secrets.ENV_VARS }}" > .env
      - name: Store SSH key
        run: echo "${{ secrets.SSH_KEY_CONTENT }}" > ${{ env.SSH_KEY_FILE_NAME }}
      - name: Change SSH key permission
        run: chmod 444 ${{ env.SSH_KEY_FILE_NAME }}
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Unzip compressed artifact
        run: unzip -o ${{ env.COMPRESSED_ARTIFACT_FILE_NAME }}
      - name: Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          source: './build,package.json,${{ env.ECOSYSTEM_CONFIG_FILE }},.env'
          target: '/home/${{ secrets.SSH_USERNAME }}/${{ env.APP_DIR }}'
      - name: Executing remote command using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            source ~/.profile
            cd /home/${{ secrets.SSH_USERNAME }}/${{ env.APP_DIR }}
            npm install --omit=dev
            pm2 reload ecosystem.staging.config.js
            pm2 save
